name: graf
services:
  neo4j:
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - db:/data/db
    image: neo4j:5.19.0
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
volumes:
  db:
